package common

import (
	"github.com/stretchr/objx"
)

const (
	UserKeyAuthCode            string = "authCode"
	UserKeyProviderCredentials string = "creds"
)

type User interface {
	// Email gets the users email address.
	Email() string

	// Name gets the users full name.
	Name() string

	// Nickname gets the users nickname or username.
	Nickname() string

	// AvatarURL gets the URL of an image representing the user.
	AvatarURL() string

	// ProviderCredentials gets a map of Credentials (by provider name).
	ProviderCredentials() map[string]*Credentials

	// IDForProvider gets the ID value for the specified provider name for
	// this user from the ProviderCredentials data.
	IDForProvider(provider string) string

	// AuthCode gets this user's globally unique ID (generated by the host program)
	AuthCode() string

	// Data gets the underlying data that makes up this User.
	Data() objx.Map
}
